#!/bin/bash
# inspiration: https://github.com/coral-xyz/anchor/blob/master/tests/cfo/scripts/localnet.sh

#kill the existing validator in case it wasn't shut down before
kill -9 $(lsof -ti:8899)

sleep 2

VALIDATOR_OUT="./validator-stdout.txt"

rm -rf ./test-ledger
rm ./validator-stdout.txt
solana-test-validator \
    --bpf-program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s ./deps/metaplex/token-metadata/target/deploy/mpl_token_metadata.so \
    --bpf-program TL1ST2iRBzuGTqLn1KXnGdSnEow62BzPnGiqyRXhWtW ./target/deploy/tensor_whitelist.so > $VALIDATOR_OUT &

sleep 2

#manually deploy old version - unfortunately can't include in --bpf-program above coz authority will be diff and we won't be able to redeploy
solana program deploy ./deps/tensorswap_v2.so --url http://localhost:8899 --program-id ./target/deploy/tensorswap-keypair.json
solana program show TSWAPaqyCSx2KABk68Shruf4rp7CxcNi8hAsbdwmHbN --url http://localhost:8899
anchor build --program-name tensorswap

sleep 2

# run just the migration test
TESTS_GLOB=tests/tswap/migration.test.ts anchor test --skip-build --skip-deploy --skip-local-validator -- --features testing

#kill the existing validator in the end so it's not running
kill -9 $(lsof -ti:8899)