name: Test JS client

on:
  workflow_call:

env:
  CACHE: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        node:
          - glob: tests/prices.spec.ts
          - glob: tests/tswap/buy.test.ts
          - glob: tests/tswap/deposit.test.ts
          - glob: tests/tswap/pool.test.ts
          - glob: tests/tswap/sell.test.ts
          - glob: tests/tswap/tswap.test.ts
          - glob: tests/tswap/withdraw.test.ts
          - glob: tests/tswap/margin.test.ts
          - glob: tests/tswap/singleListing.test.ts
          - glob: tests/twhitelist/whitelist.test.ts
          - glob: tests/twhitelist/mint_proof.test.ts
          - glob: tests/twhitelist/merkle_tree.test.ts
          - glob: tests/tbid/tbid.test.ts
          - glob: tests/tswap/t22_buy.test.ts
          - glob: tests/tswap/t22_deposit.test.ts
          - glob: tests/tswap/t22_sell.test.ts
          - glob: tests/tswap/t22_withdraw.test.ts
          - glob: tests/tswap/t22_singleListing.test.ts
          - glob: tests/tswap/wns_buy.test.ts
          - glob: tests/tswap/wns_deposit.test.ts
          - glob: tests/tswap/wns_sell.test.ts
          - glob: tests/tswap/wns_withdraw.test.ts
          - glob: tests/tswap/wns_singleListing.test.ts
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Load environment variables
        run: cat .github/.env >> $GITHUB_ENV

      - name: Start validator
        uses: tensor-foundation/actions/start-validator@v1
        with:
          node: "18.x"
          solana: ${{ env.SOLANA_VERSION }}
          cache: ${{ env.CACHE }}

      - name: Install dependencies
        working-directory: ./clients/anchor
        run: yarn install
  
      - name: Build
        working-directory: ./clients/anchor
        run: yarn build

      - name: Test
        working-directory: ./clients/anchor
        run: ./anchor-test.sh
        env:
          TESTS_GLOB: ${{ matrix.node.glob }}
