name: Test JS client

on:
  workflow_call:

env:
  CACHE: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        node:
          - glob: tests/prices.spec.ts
          - glob: tests/tswap/margin.test.ts
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Load environment variables
        run: cat .github/.env >> $GITHUB_ENV

      - name: Start validator
        uses: tensor-foundation/actions/start-validator@v2
        with:
          node: "18.x"
          solana: ${{ env.SOLANA_VERSION }}
          cache: ${{ env.CACHE }}

      - name: Install dependencies
        working-directory: ./clients/anchor
        run: yarn install
  
      - name: Build
        working-directory: ./clients/anchor
        run: yarn build

      - name: Test
        working-directory: ./clients/anchor
        run: ./anchor-test.sh
        env:
          TESTS_GLOB: ${{ matrix.node.glob }}
