name: Test JS client

on: [workflow_dispatch, workflow_call]

env:
  CACHE: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["18.x", "20.x"]
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Load environment variables
        run: cat .github/.env >> $GITHUB_ENV
      
      - name: Check for .only or .skip in AVA tests
        run: |
          if grep -R --include="*.js" -E "(test|it|describe)\.(only|skip)" ./clients/js/tests/; then
            echo "Error: Found .only or .skip in JS Client tests. Please remove them before committing."
            exit 1
          else
            echo "No .only or .skip found in JS Client tests."
          fi

      - name: Start validator
        uses: tensor-foundation/actions/start-validator@v2
        with:
          node: ${{ matrix.node }}
          solana: ${{ env.SOLANA_VERSION }}
          cache: ${{ env.CACHE }}

      - name: Install dependencies
        uses: tensor-foundation/actions/install-node-dependencies@v2
        with:
          folder: ./clients/js
          cache: ${{ env.CACHE }}
          key: clients-js

      - name: Build
        working-directory: ./clients/js
        run: pnpm build

      - name: Test
        working-directory: ./clients/js
        run: pnpm test
